### PR TITLE
fix: changes/fixes as a result of testing

### LINKED ISSUE #80: Move provider image out of dockerhub
Docker's rate limits keep being hit, so we should move to ghcr or gcr, whatever you think is best.

Off the top of my head things need to be updated in Makefile, the release action, the manager_image_patch.yaml and the env secrets in github. you should then be able to trigger the release build and stuff should go to the right place.

### LINKED ISSUE #83: Only delete MicroVMs if state is CREATED or PENDING
Currently when deleting a microvm machine we Get the mvm and check if it is not nil and then delete.

But, we should only issue a delete request to mvms that are not already deleting.

The states on an MVM are:
- CREATED
- PENDING
- DELETING

### LINKED ISSUE #84: Network interface creation error
**What happened:**
When creating a microvm via capmvm i am seeing an error with creating the network interface quite a lot:

```
time="2022-01-11T07:54:18Z" level=debug msg="running step to create network interface" controller=microvm iface=eth1 step=network_iface_create
time="2022-01-11T07:54:18Z" level=debug msg="checking if network interface exists" controller=microvm iface=flvtap6af0807 service=netlink_network
time="2022-01-11T07:54:18Z" level=debug msg="creating network interface with type macvtap and MAC e7:75:08:8b:ca:fc using parent enx8cae4cd66035" controller=microvm iface=flvtap6af0807 service=netlink_network
time="2022-01-11T07:54:18Z" level=trace msg="added mac address e7:75:08:8b:ca:fc to interface" controller=microvm iface=flvtap6af0807 service=netlink_network
time="2022-01-11T07:54:18Z" level=error msg="failed executing plan" controller=microvm execution_id=01FS422W641CG1CYCHVNVCS3MH execution_time=3.596904ms num_steps=1 plan_name=microvm_create_update
time="2022-01-11T07:54:18Z" level=info msg="[3/10] reconciliation failed, rescheduled for next attempt at 2022-01-11 07:55:18 +0000 GMT" action=reconcile controller=microvm vmid=default/mvm-test-control-plane-zc6b
time="2022-01-11T07:54:18Z" level=debug msg="saving microvm spec default/mvm-test-control-plane-zc6bk" controller=microvm repo=containerd_microvm
time="2022-01-11T07:54:18Z" level=error msg="failed to reconcile vmid default/mvm-test-control-plane-zc6bk: executing plan: executing plan steps: executing steps: executing step network_iface_create: creating network interface: creating interface flvtap6af0807 using netlink: cannot assign requested address" controller=microvm
```

The main  appears to be: `creating interface flvtap6af0807 using netlink: cannot assign requested address`.

This blocks the creation of the vm.

There isn't a network interface with the same mac address:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether e0:4f:43:e6:0d:f1 brd ff:ff:ff:ff:ff:ff
3: enx8cae4cd66035: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 8c:ae:4c:d6:60:35 brd ff:ff:ff:ff:ff:ff
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:60:69:f3 brd ff:ff:ff:ff:ff:ff
5: br-0c0ac660e96b: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:46:4f:6f:93 brd ff:ff:ff:ff:ff:ff
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:a8:f7:9e:64 brd ff:ff:ff:ff:ff:ff
12: veth3d11028@if11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-0c0ac660e96b state UP mode DEFAULT group default 
    link/ether 7a:7c:5a:f9:3b:85 brd ff:ff:ff:ff:ff:ff link-netnsid 0
13: fltap433ec27: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN mode DEFAULT group default qlen 1000
    link/ether e2:ab:46:ff:79:ae brd ff:ff:ff:ff:ff:ff

```

**What did you expect to happen:**

**How to reproduce it:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- flintlock version:
- containerd version:
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by richardcase**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #84
Fixes: #83
Fixes: #80  

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Callisto13** [comment]
looks like you are also doing https://github.com/weaveworks/cluster-api-provider-microvm/issues/80, make sure you don't miss the release gh action

**Comment by Callisto13** [comment]
you can then do a release once merged (there is a doc)

**Review by yitsushi — APPROVED** [review]

File: api/v1alpha1/defaults.go [hunk 1]
```diff
@@ -0,0 +1,13 @@
+package v1alpha1
+
+import (
+	"github.com/yitsushi/macpot"
+)
+
+func SetDefaults_NetworkInterface(obj *NetworkInterface) { //nolint: revive,stylecheck
+	if obj.GuestMAC == "" {
+		mac, _ := macpot.New(macpot.AsLocal(), macpot.AsUnicast())
```
Comment (Callisto13) [inline api/v1alpha1/defaults.go:9]: could this error? do we care?

File: config/default/manager_image_patch.yaml [hunk 2]
```diff
@@ -7,5 +7,5 @@ spec:
   template:
     spec:
       containers:
-      - image: docker.io/weaveworks/cluster-api-microvm-controller:latest
+      - image: ghcr.io/weaveworks/cluster-api-provider-microvm:dev
```
Comment (Callisto13) [inline config/default/manager_image_patch.yaml:10]: was leaving the `dev` tag intentional?

File: controllers/microvmmachine_controller.go [hunk 3]
```diff
@@ -209,12 +209,13 @@ func (r *MicrovmMachineReconciler) reconcileNormal(ctx context.Context, machineS
...
 		return ctrl.Result{}, nil
 	}
+	machineScope.V(defaults.LogLevelDebug).Info("Bootstrap secret is ready", "machine", machineScope.MvmMachine.Name, "secret", machineScope.Machine.Spec.Bootstrap.DataSecretName)
 
 	mvmSvc, err := r.getMicrovmService(machineScope)
 	if err != nil {
 		machineScope.Error(err, "failed to get microvm machine")
 
-		return ctrl.Result{}, nil
+		return ctrl.Result{}, err
```
Comment (Callisto13) [inline controllers/microvmmachine_controller.go:218]: lol

File: internal/services/microvm/service.go [hunk 4]
```diff
@@ -43,20 +44,20 @@ func New(scope *scope.MachineScope, client Client) *Service {
...
+	if err := s.addMetadata(apiMicroVM, providerID); err != nil {
 		return fmt.Errorf("adding metadata: %w", err)
 	}
 
 	for i := range apiMicroVM.Interfaces {
 		iface := apiMicroVM.Interfaces[i]
 
 		if iface.GuestMac == nil || *iface.GuestMac == "" {
-			mac, err := macpot.New(macpot.AsLocal())
+			mac, err := macpot.New(macpot.AsLocal(), macpot.AsUnicast())
```
Comment (Callisto13) [inline internal/services/microvm/service.go:60]: is this happening twice then? once in defaults and again here?

File: templates/cluster-template-cilium.yaml [hunk 5]
```diff
@@ -0,0 +1,926 @@
+# To use this template ensure the cluster resource set feature flag is set by:
+# export EXP_CLUSTER_RESOURCE_SET=true
```
Comment (Callisto13) [inline templates/cluster-template-cilium.yaml:2]: is that var picked up at the `clusterctl generate`?
so can users optionally not have cilium and use the other template?
how do you indicate to clusterctl which template you want from the release? (googles)

Comment (Callisto13) [reply templates/cluster-template-cilium.yaml:2]: > how do you indicate to clusterctl which template you want from the release? (googles)

ugh with a path. gross.

can you update the release action to make sure it is published?

File: api/v1alpha1/defaults.go (hunk 1 above)
Comment (richardcase) [reply api/v1alpha1/defaults.go:9]: It could error but its ok as we try in the actual reconciler again and that will report the error.

File: config/default/manager_image_patch.yaml (hunk 2 above)
Comment (richardcase) [reply config/default/manager_image_patch.yaml:10]: Yes it was intentional

Comment (richardcase) [reply config/default/manager_image_patch.yaml:10]: Its required to get working in tilt.

File: internal/services/microvm/service.go (hunk 4 above)
Comment (richardcase) [reply internal/services/microvm/service.go:60]: Yes, i left the `defaults` one in there as an example of how to create a default....i didn't see any harm having 2. But happy to remove it if the sample isn't helpful

File: config/default/manager_image_patch.yaml (hunk 2 above)
Comment (Callisto13) [reply config/default/manager_image_patch.yaml:10]: can you change this bit then: https://github.com/weaveworks/cluster-api-provider-microvm/blob/main/.github/workflows/release.yml#L39

Comment (Callisto13) [reply config/default/manager_image_patch.yaml:10]: and add that new cilium template to the list of files https://github.com/weaveworks/cluster-api-provider-microvm/blob/main/.github/workflows/release.yml#L50

File: templates/cluster-template-cilium.yaml (hunk 5 above)
Comment (richardcase) [reply templates/cluster-template-cilium.yaml:2]: For the cilium you use:

```bash
clusterctl generate cluster mycluster --flavor cilium.....
```

Comment (richardcase) [reply templates/cluster-template-cilium.yaml:2]: The `EXP_CLUSTER_RESOURCE_SET` needs to be set before clusterctl init
